app/layout.tsx
app/page.tsx
components/banner/__tests__/index.tsx
components/banner/index.tsx
components/columns/index.tsx
constants/index.ts
interfaces/discord/index.ts

closes #12 
closes #54 
closes #55

Download page

---

components/columnCards/index.tsx
components/table/tableData/index.tsx
components/table/tableData/tooltip/index.tsx
constants/index.ts
utils/findTopFive/index.ts
utils/secondsToSexagesimal/__tests__/index.ts
utils/secondsToSexagesimal/index.ts

Format round times

---

app/how-to-play/layout.tsx
app/layout.tsx
app/leaderboard/layout.tsx
app/leaderboard/page.tsx
app/stats/[slug]/layout.tsx
app/stats/[slug]/page.tsx
components/banner/styled.ts
components/pageHeader/styled.ts
components/table/index.tsx
components/tableWithControls/index.tsx
components/tableWithControls/pagination/__tests__/index.tsx
components/tableWithControls/pagination/index.tsx
components/tableWithControls/pagination/styled.ts
constants/index.ts
pages/api/stats/index.ts
pages/api/times/index.ts

To do:
Evaluate to create a new PR after the pagination is done, since the all stats pages could be already usable with the pagination

Create pages for all stats

---

app/leaderboard/page.tsx
app/stats/[slug]/page.tsx
components/columnCards/index.tsx
components/info/__tests__/index.tsx
components/info/index.tsx
components/info/styled.ts
components/table/index.tsx
components/table/tableData/index.tsx
components/tableWithControls/badges/__tests__/index.tsx
components/tableWithControls/badges/index.tsx
components/tableWithControls/badges/styled.ts
components/tableWithControls/index.tsx
constants/index.ts
interfaces/difficulty/index.ts
interfaces/player/index.ts
pages/api/scoreboard/index.ts
pages/api/stats/index.ts
pages/api/times/index.ts
utils/getSortConditionByKey/__tests__/index.ts
utils/getSortConditionByKey/index.ts

Filter table by difficulty

---

README.md
app/leaderboard/page.tsx
components/table/index.tsx
components/table/tableData/tooltip/index.tsx
components/tableWithControls/badges/index.tsx
components/tableWithControls/badges/styled.ts
theme/dark/index.ts

Fix a11y issues

---

utils/calculateBestTimeByDifficulty/__tests__/index.ts
utils/calculateBestTimeByDifficulty/index.ts

Fix dnf issue

---

app/leaderboard/page.tsx
components/columnCards/index.tsx
components/columnCards/styled.ts
components/footer/index.tsx
components/link/styled.ts
components/navbar/desktop/index.tsx
components/navbar/mobile/index.tsx
components/tableWithControls/index.tsx
constants/index.ts
pages/api/scoreboard/index.ts

Make view all more visible

---

components/awards/index.tsx
components/awards/styled.ts
constants/index.ts
pages/api/player/index.ts
public/sitemap-0.xml
public/sitemap.xml
utils/formatGameAwards/index.ts

Player page mobile

---

components/table/components/tableData/battleTag/styled.ts
components/table/components/tableData/challenges/__tests__/index.tsx
components/table/components/tableData/challenges/index.tsx
components/table/components/tableData/challenges/styled.ts
components/table/components/tableData/index.tsx
constants/index.ts
interfaces/player/index.ts
pages/api/scoreboard/index.ts
pages/api/stats/index.ts
utils/calculateCompletedChallenges/__tests__/index.ts
utils/calculateCompletedChallenges/index.ts
utils/getSortConditionByKey/__tests__/index.ts
utils/getSortConditionByKey/index.ts

Tournament rewards

---

app/layout.tsx
app/leaderboard/page.tsx
app/stats/[slug]/page.tsx
components/icons/clock/index.tsx
components/icons/stats/index.tsx
components/navbar/components/desktop/index.tsx
components/scoreboardSelector/index.tsx
components/table/index.tsx
components/tableWithControls/index.tsx
components/toggle/__tests__/index.tsx
components/toggle/index.tsx
components/toggle/styled.ts
constants/index.ts

Add breadcrumbs

---

components/scoreboardSelector/index.tsx
components/toggle/styled.ts
utils/getSortConditionByKey/index.ts

Fix sort save streak

---

components/navbar/components/desktop/index.tsx
components/navbar/components/mobile/index.tsx
constants/index.ts
interfaces/player/index.ts
pages/api/scoreboard/index.ts
pages/api/stats/index.ts
pages/api/timeLeaderboard/index.ts
pages/api/times/index.ts
utils/calculateCompletedChallenges/index.ts
utils/removeBlacklistedPlayers/index.ts

Ffilter local player

---

atomicStructureCheck.py

feat: create script to validate imports for components

---

.github/workflows/code-quality.yml
.github/workflows/components-structure.yml

Add new checks to ci

---

.github/workflows/auto-close-issue.yml
.github/workflows/code-quality.yml
.github/workflows/components-structure.yml
app/layout.tsx
app/leaderboard/page.tsx
app/player/[slug]/page.tsx
app/stats/[slug]/page.tsx
components/atoms/toast/index.tsx
components/atoms/toast/styled.ts
components/molecules/downloadModal/index.tsx
components/molecules/playerFinder/index.tsx
components/organisms/bestGamesWithControls/index.tsx
components/organisms/columnCardsWithControls/index.tsx
components/organisms/tableWithControls/index.tsx
components/templates/leaderboard/index.tsx
components/templates/playerDashboard/index.tsx
hooks/useToast/__tests__/index.tsx
hooks/useToast/index.tsx
interfaces/toast/index.ts

Automatically detected issues: Closes #158

Handle errors with toast

---

package.json
yarn.lock

Automatically detected issues: Closes #201

fix #201: update next js

---

app/stats/[slug]/page.tsx
components/molecules/columnCards/index.tsx
components/organisms/columnCardsWithControls/index.tsx

Automatically detected issues: Closes #214

fix #214: fix link from leaderboard to scoreboard

---

components/molecules/bestGames/components/card/styled.ts
components/molecules/bestGames/components/highlightCard/styled.ts
components/molecules/bestGames/styled.ts
components/templates/playerDashboard/index.tsx
hooks/useToast/index.tsx

Automatically detected issues: Closes #212 #214

Fix mobile styles for best game times leaderboard

---

components/atoms/pageContainer/styled.ts
components/organisms/columnsWithComparison/index.tsx
components/templates/playerDashboard/index.tsx
constants/index.ts
interfaces/difficulty/index.ts
interfaces/player/index.ts
utils/formatComparePlayer/__tests__/index.ts
utils/formatComparePlayer/index.tsx
utils/formatRoundsData/__tests__/index.ts
utils/formatRoundsData/index.ts
utils/getSortConditionByKey/index.ts

Automatically detected issues: Closes #203 #218

fix player comparison and add solo best times

---

components/atoms/button/index.tsx
components/atoms/button/styled.ts
components/molecules/badges/__tests__/index.tsx
components/molecules/badges/index.tsx
components/molecules/columnCards/index.tsx
components/organisms/columnCardsWithControls/index.tsx

Automatically detected issues: Closes #223

feature #223: solo times leaderboard

---

app/leaderboard/page.tsx
components/molecules/columnCards/components/loaderCard/index.tsx
components/molecules/columnCards/components/row/__tests__/index.tsx
components/molecules/columnCards/components/row/index.tsx
components/molecules/columnCards/components/row/styled.ts
components/molecules/columnCards/index.tsx
components/molecules/columnCards/styled.ts
components/organisms/columnCardsWithControls/index.tsx
components/templates/leaderboard/index.tsx
interfaces/leaderboard/index.ts
pages/api/leaderboard/index.ts
utils/findTopFive/__tests__/index.ts
utils/findTopFive/index.ts

Automatically detected issues: Closes #222

Make leaderboard naems clickable

---

components/molecules/columns/index.tsx
components/molecules/columns/styled.tsx
components/molecules/winStreak/index.tsx
components/molecules/winStreak/styled.ts
components/templates/playerDashboard/index.tsx
components/templates/playerDashboard/styled.ts
constants/index.ts
constants/mock/index.ts
interfaces/player/index.ts
pages/api/player/[battleTag].ts

Automatically detected issues: Closes #234

current win streak to player page

---

components/atoms/tabs/__tests__/index.tsx
components/atoms/tabs/index.tsx
components/atoms/tabs/styled.ts
components/templates/playerDashboard/index.tsx
constants/index.ts
pages/api/player/[battleTag].ts
utils/playerDataOutdated/__tests__/index.ts
utils/playerDataOutdated/index.ts

Automatically detected issues: Closes #162

Relic comparison

---

components/atoms/tabs/index.tsx
components/templates/leaderboard/index.tsx

Automatically detected issues: Closes #242

feature #242: add kibble tab disabled

---

components/molecules/winStreak/index.tsx
components/molecules/winStreak/styled.ts
components/organisms/playerFinderWithResult/index.tsx
components/templates/playerDashboard/index.tsx
constants/index.ts
utils/formatComparePlayer/index.tsx
utils/getSortConditionByKey/index.ts

Automatically detected issues: Closes #255

feat #255: add colored border when current win streak is higher than 10

---

.github/workflows/components-structure.yml
.github/workflows/unused-components.yml
.github/workflows/unused-resources.yml
scripts/atomicStructureCheck.py
scripts/findUnusedResources.py
scripts/unusedComponentsCheck.py

The new script should be able to detect unused components
The new script should be able to detect unused resources (and deleted if executed with -d option)
Update path for import script

CI improvements

---

components/atoms/tooltip/styled.ts
components/molecules/columnCards/components/loaderCard/__tests__/index.tsx
components/molecules/columnCards/components/row/__tests__/index.tsx
components/templates/playerDashboard/components/Header/__tests__/index.tsx
components/templates/playerDashboard/components/Header/index.tsx
components/templates/playerDashboard/components/Header/styled.ts
components/templates/playerDashboard/components/besties/index.tsx
components/templates/playerDashboard/components/besties/styled.ts
components/templates/playerDashboard/index.tsx
constants/index.ts
interfaces/player/index.ts
pages/api/playerTopPositions/[battleTag].ts
utils/formatPlayerTops/index.ts

Automatically detected issues: Closes #289

feat #289: wip

---

components/atoms/paws/__tests__/index.tsx
components/atoms/paws/index.tsx
components/atoms/paws/styled.ts
components/molecules/bestGames/components/card/index.tsx
components/molecules/table/components/tableData/difficulty/index.tsx
components/molecules/table/components/tableData/index.tsx
components/molecules/table/components/tableData/styled.ts

Automatically detected issues: Closes #258

feat #258: create paws component

---

components/atoms/paws/index.tsx
components/molecules/table/components/tableData/index.tsx
components/molecules/table/components/tableData/tooltip/index.tsx
constants/index.ts
interfaces/difficulty/index.ts
interfaces/player/index.ts
pages/api/leaderboard/index.ts
pages/api/player/[battleTag].ts
pages/api/stats/index.ts
theme/dark/index.ts
theme/light/index.ts
utils/calculateBestTimeByDifficulty/__tests__/index.ts
utils/calculateBestTimeByDifficulty/index.ts
utils/calculateTotals/__tests__/index.ts
utils/calculateTotals/index.ts
utils/formatRoundsData/__tests__/index.ts
utils/formatRoundsData/index.ts

Automatically detected issues: Closes #313

feat #313: add nightmare to difficulty types

---

components/molecules/badges/styled.ts

Automatically detected issues: Closes #317

fix #317: fix badges overflow
